
heat_template_version: 2015-04-30
parameters:
  param1:
    type: string
    default: param-default-depth1-more-text-for-a-long-string-more-text-for-a-long-string-more-text-for-a-long-string
resources:
  res1_0:
    type: My::Nested2
    properties:
      param1: {get_param: param1}
  res1_1:
    type: My::Nested2
    properties:
      param1: {get_param: param1}
outputs:
  output:
    value: {list_join: ['.', [ {get_attr: [res1_0, output] }, {get_attr: [res1_1, output] } ] ]}
